---
title: 'Project 1: Present Data Visualization'
output:
  html_document:
    df_print: paged
---

Julia Higdon
Brianna Solis 
Section 02
10-17-2021

```{r}
library(tidyverse)
library(ggplot2)
library(vioplot)
library(viridis)
```

```{r}
library(readr)
AmericanKennelClub.data <- read_csv("AmericanKennelClubBreedsBySize (4).csv")
#View(AmericanKennelClub.data)
```

```{r}
AmericanKennelClub.data$`Size Category` <- factor(AmericanKennelClub.data$`Size Category`, levels = c("X-Small","Small", "Medium", "Large", "X-Large"))

ggplot(AmericanKennelClub.data, aes(x= `Size Category` , y= `Avg Weight (pounds)`)) + 
    geom_violin() + xlab("Size of Dogs") + 
    ylab("Average Weight (lbs.)") + 
    ggtitle("Size of Dogs Compared to Relative Weight") + 
    geom_violin(colour="brown", fill="pink") + 
    stat_summary(fun="mean", geom= "crossbar", width=1, size=0.2, colour="blue") + 
    theme_bw() +
    scale_y_continuous(breaks=seq(0,200,20)) 
```

```{r}
loop.vector <- 1:4

for (i in loop.vector) { 
  
  y <- names(c("X-Small", "Small", "Medium", "Large", "X-Large"))
  print(vioplot(AmericanKennelClub.data$`Avg Weight (pounds)` ~ AmericanKennelClub.data$`Size Category`,
        pch = 22, 
        col=viridis(5), 
        names=c("X-Small", "Small", "Medium", "Large", "X-Large"), 
        xlab= "Dog Size",
        ylab= "Average Weight (Pounds)", 
        main= "Average Weight for Each Dog Size"))
}
```